# Generated by Django 2.2 on 2019-09-21 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fundooapi', '0003_auto_20190919_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundoouser',
            name='age',
        ),
        migrations.AddField(
            model_name='fundoouser',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='fundoouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FunNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(max_length=1025)),
                ('reminder', models.DateTimeField()),
                ('collaborator', models.EmailField(max_length=255)),
                ('color', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
