# Generated by Django 2.2 on 2019-09-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fundooapi', '0004_auto_20190921_1337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunNotes',
        ),
    ]
